activity_auto_refresh: true
activity_refresh_interval: 30
always_on_top: false
auto_refresh_enabled: true
auto_refresh_interval: 25
card_spacing: 5
compact_view_enabled: false
debug_modes:
  api_calls: false
  general: false
  notifications: false
  project_load_profiler: true
  suppress_qt_multimedia_warnings: true
  ui_updates: false
django_username: 1
enable_activity_page: true
enable_assignment_board: true
enable_import_page: true
enable_review_page: true
enable_xml_import_page: true
last_job_id: 83
last_scroll_position: 0
last_timeline_index: 0
notifications: 'off'
notifications_animations: false
notifications_do_not_disturb: false
notifications_lifetime: 16
notifications_size: large
notifications_subtle: false
nuke_exe_path: ''
nukedash_filter_state:
  artist_id: 1
  enabled: true
  show_hidden_shots: false
  show_hidden_tasks: false
  show_to_conform: false
  sort_mode: title_asc
  status_values:
  - approved
  - assigned
  - in_progress
  - not_started
  - rejected
  - unassigned
  - waiting_for_approval
nukedash_task_style: checklist
polling_interval: 25
preview_output_subdir: renders/precomp/previews
preview_overwrite: true
preview_quality: medium
preview_thumbnail_size: Small
remember_last_session: true
remember_window_size: true
row_height: 5
server_url: http://192.168.10.207:8000
shots_layout_mode: grid
show_startup_loading_dialog: true
startup_tab: 0
theme_file: dark_v01.qss
threede_exe_path: /home/rockybtw/Documents/3DE4_linux64_r8.1/bin/3DE4
window_height: 1419
window_width: 1280
window_x: 2560
window_y: 0
